inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml


AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'active_encode.gemspec'
    - 'vendor/**/*'

Rails/RakeEnvironment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
